name: flutter_clean_riverpod
description: "A comprehensive Flutter sample project demonstrating Clean Architecture principles, state management with Riverpod, and responsive UI design. This project serves as a reference implementation for building scalable Flutter applications."

publish_to: 'none' # This is a sample project for educational purposes

version: 1.0.9+10

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.2.0
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.6.1
  flutter_svg: ^2.0.17
  animated_custom_dropdown: ^3.1.1
  json_annotation: ^4.9.0
  go_router: ^11.1.4
  flutter_localizations:
    sdk: flutter
  bot_toast: ^4.1.3
  intl: ^0.20.2
  pinput: ^5.0.0
  table_calendar: ^3.2.0
  dotted_line: ^3.2.3
  syncfusion_flutter_pdfviewer: ^30.1.37
  dio: ^5.7.0
  get_it: ^8.0.2
  retrofit: ^4.4.1
  dartz: ^0.10.1
  curl_logger_dio_interceptor: ^1.0.0
  flutter_secure_storage: ^9.2.2
  flutter_secure_storage_web:
  logger: ^2.5.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  cached_network_image_web: ^1.3.1
  flutter_cache_manager: ^3.4.1
  lottie: ^3.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  flutter_image_compress: ^2.3.0
  http: ^1.2.2
  file_picker: ^8.1.4
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^8.3.0
  video_player: ^2.9.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  retrofit_generator: ^8.2.1
  very_good_analysis: ^6.0.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

  flutter_lints: ^3.0.2

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/animations/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
